import { NavigationTree } from "@/@types/navigation";
import { NAV_ITEM_TYPE_COLLAPSE, NAV_ITEM_TYPE_ITEM } from "@/constants/navigation.constant";

export const ROLE_MENUS: Record<string, NavigationTree[]> = {
  SUPER_ADMIN: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "tenants.management",
      path: "",
      title: "Tenants Management",
      translateKey: "nav.tenants.management",
      icon: "building",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "tenants.list",
          path: "/tenants/list",
          title: "List Tenants",
          translateKey: "nav.tenants.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "tenants.create",
          path: "/tenants/create",
          title: "Create Tenant",
          translateKey: "nav.tenants.create",
          icon: "plus",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "tenants.subscription",
          path: "/tenants/subscription",
          title: "Subscription Management",
          translateKey: "nav.tenants.subscription",
          icon: "credit-card",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "users",
      path: "",
      title: "Users",
      translateKey: "nav.users",
      icon: "users",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "users.list",
          path: "/users/list",
          title: "List All Users",
          translateKey: "nav.users.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "users.assign.roles",
          path: "/users/assign-roles",
          title: "Assign Roles",
          translateKey: "nav.users.assign.roles",
          icon: "key",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "clinics",
      path: "",
      title: "Clinics",
      translateKey: "nav.clinics",
      icon: "hospital",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "clinics.list",
          path: "/clinics/list",
          title: "List Clinics",
          translateKey: "nav.clinics.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "clinics.create",
          path: "/clinics/create",
          title: "Create Clinic",
          translateKey: "nav.clinics.create",
          icon: "plus",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "analytics",
      path: "",
      title: "Analytics / Reports",
      translateKey: "nav.analytics",
      icon: "bar-chart",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "analytics.stats",
          path: "/analytics/stats",
          title: "System-wide Statistics",
          translateKey: "nav.analytics.stats",
          icon: "activity",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "analytics.outbreaks",
          path: "/analytics/outbreaks",
          title: "Outbreaks / Data Events",
          translateKey: "nav.analytics.outbreaks",
          icon: "alert-circle",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "audit.logs",
      path: "/audit-logs",
      title: "Audit Logs",
      translateKey: "nav.audit.logs",
      icon: "file-text",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "settings",
      path: "/settings",
      title: "Settings",
      translateKey: "nav.settings",
      icon: "settings",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
  ],

  // ------------------------------------------------------
  // TENANT_ADMIN
  // ------------------------------------------------------

  TENANT_ADMIN: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "clinics",
      path: "",
      title: "Clinics",
      translateKey: "nav.clinics",
      icon: "hospital",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "clinics.list",
          path: "/clinics/list",
          title: "List Clinics",
          translateKey: "nav.clinics.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "clinics.edit",
          path: "/clinics/edit",
          title: "Create / Edit Clinics",
          translateKey: "nav.clinics.edit",
          icon: "edit",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "users",
      path: "",
      title: "Users",
      translateKey: "nav.users",
      icon: "users",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "users.list",
          path: "/users/list",
          title: "List Users",
          translateKey: "nav.users.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "users.assign.roles",
          path: "/users/assign-roles-clinics",
          title: "Assign Roles within Clinics",
          translateKey: "nav.users.assign.roles.clinics",
          icon: "key",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "appointments.visits",
      path: "/appointments",
      title: "Appointments & Visits",
      translateKey: "nav.appointments.visits",
      icon: "calendar",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "patients",
      path: "",
      title: "Patients",
      translateKey: "nav.patients",
      icon: "users",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "patients.list",
          path: "/patients/list",
          title: "List Patients",
          translateKey: "nav.patients.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "patients.add.edit",
          path: "/patients/add-edit",
          title: "Add / Edit Patients",
          translateKey: "nav.patients.add.edit",
          icon: "edit",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "analytics",
      path: "/analytics",
      title: "Analytics / Reports",
      translateKey: "nav.analytics",
      icon: "bar-chart",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "audit.logs",
      path: "/audit-logs",
      title: "Audit Logs",
      translateKey: "nav.audit.logs",
      icon: "file-text",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "clinic.settings",
      path: "/clinic-settings",
      title: "Clinic Settings",
      translateKey: "nav.clinic.settings",
      icon: "settings",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
  ],

  // ------------------------------------------------------
  // CLINIC_ADMIN
  // ------------------------------------------------------

  CLINIC_ADMIN: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "staff.management",
      path: "",
      title: "Users / Staff Management",
      translateKey: "nav.staff.management",
      icon: "users",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "staff.list",
          path: "/staff/list",
          title: "List Staff",
          translateKey: "nav.staff.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "staff.assign.roles",
          path: "/staff/assign-roles",
          title: "Assign Roles",
          translateKey: "nav.staff.assign.roles",
          icon: "key",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "appointments",
      path: "/appointments",
      title: "Appointments & Visits",
      translateKey: "nav.appointments",
      icon: "calendar",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "patients",
      path: "",
      title: "Patients",
      translateKey: "nav.patients",
      icon: "users",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "patients.list",
          path: "/patients/list",
          title: "List Patients",
          translateKey: "nav.patients.list",
          icon: "list",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "patients.add.edit",
          path: "/patients/add-edit",
          title: "Add / Edit Patient Info",
          translateKey: "nav.patients.add.edit",
          icon: "edit",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "visits",
      path: "",
      title: "Visits",
      translateKey: "nav.visits",
      icon: "activity",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "visits.diagnoses",
          path: "/visits/diagnoses",
          title: "Record Diagnoses",
          translateKey: "nav.visits.diagnoses",
          icon: "clipboard",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "visits.prescriptions",
          path: "/visits/prescriptions",
          title: "Prescriptions",
          translateKey: "nav.visits.prescriptions",
          icon: "file-plus",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "visits.lab.orders",
          path: "/visits/lab-orders",
          title: "Lab Orders",
          translateKey: "nav.visits.lab.orders",
          icon: "flask",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "vaccinations",
      path: "/vaccinations",
      title: "Vaccinations",
      translateKey: "nav.vaccinations",
      icon: "shield",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "clinic.settings",
      path: "/clinic-settings",
      title: "Clinic Settings",
      translateKey: "nav.clinic.settings",
      icon: "settings",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
  ],

  // ------------------------------------------------------
  // DOCTOR
  // ------------------------------------------------------

  DOCTOR: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "appointments",
      path: "/my-appointments",
      title: "My Appointments",
      translateKey: "nav.my.appointments",
      icon: "calendar",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "my.patients",
      path: "/my-patients",
      title: "My Patients",
      translateKey: "nav.my.patients",
      icon: "users",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "visits.encounters",
      path: "",
      title: "Visits / Encounters",
      translateKey: "nav.visits.encounters",
      icon: "activity",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "visits.diagnoses",
          path: "/visits/diagnoses",
          title: "Record Diagnoses",
          translateKey: "nav.visits.diagnoses",
          icon: "clipboard",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "visits.prescriptions",
          path: "/visits/prescriptions",
          title: "Prescriptions",
          translateKey: "nav.visits.prescriptions",
          icon: "edit",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
        {
          key: "visits.lab",
          path: "/visits/lab-orders",
          title: "Lab Orders",
          translateKey: "nav.visits.lab",
          icon: "flask",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "patient.notes",
      path: "/patient-notes",
      title: "Patient Notes",
      translateKey: "nav.patient.notes",
      icon: "file-text",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "vaccinations",
      path: "/vaccinations",
      title: "Vaccinations",
      translateKey: "nav.vaccinations",
      icon: "shield",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
  ],

  // ------------------------------------------------------
  // STAFF
  // ------------------------------------------------------

  STAFF: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
    {
      key: "patients",
      path: "",
      title: "Patients",
      translateKey: "nav.patients",
      icon: "users",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "patients.basic.info",
          path: "/patients/basic-info",
          title: "Add / Edit Basic Info",
          translateKey: "nav.patients.basic.info",
          icon: "edit",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "appointments",
      path: "",
      title: "Appointments",
      translateKey: "nav.appointments",
      icon: "calendar",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "appointments.book.cancel",
          path: "/appointments/book-cancel",
          title: "Book / Cancel",
          translateKey: "nav.appointments.book.cancel",
          icon: "calendar-check",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "visits",
      path: "",
      title: "Visits",
      translateKey: "nav.visits",
      icon: "activity",
      type: NAV_ITEM_TYPE_COLLAPSE,
      authority: ["editable"],
      subMenu: [
        {
          key: "visits.notes",
          path: "/visits/basic-notes",
          title: "Record Basic Symptoms / Notes",
          translateKey: "nav.visits.notes",
          icon: "clipboard",
          type: NAV_ITEM_TYPE_ITEM,
          authority: ["editable"],
          subMenu: [],
        },
      ],
    },
    {
      key: "vaccinations",
      path: "/vaccinations",
      title: "Vaccinations",
      translateKey: "nav.vaccinations",
      icon: "shield",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["editable"],
      subMenu: [],
    },
  ],

  // ------------------------------------------------------
  // ANALYST
  // ------------------------------------------------------

  ANALYST: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "patients",
      path: "/patients",
      title: "Patients",
      translateKey: "nav.patients",
      icon: "users",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "visits",
      path: "/visits",
      title: "Visits / Diagnoses / Prescriptions",
      translateKey: "nav.visits",
      icon: "activity",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "appointments",
      path: "/appointments",
      title: "Appointments",
      translateKey: "nav.appointments",
      icon: "calendar",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "lab.orders",
      path: "/lab-orders",
      title: "Lab Orders",
      translateKey: "nav.lab.orders",
      icon: "flask",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "vaccinations",
      path: "/vaccinations",
      title: "Vaccinations",
      translateKey: "nav.vaccinations",
      icon: "shield",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "data.events",
      path: "/events",
      title: "Data Events / Outbreak Predictions",
      translateKey: "nav.data.events",
      icon: "alert-circle",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "export.data",
      path: "/export-data",
      title: "Export Data",
      translateKey: "nav.export.data",
      icon: "download",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
  ],

  // ------------------------------------------------------
  // VIEWER
  // ------------------------------------------------------

  VIEWER: [
    {
      key: "dashboard",
      path: "/dashboard",
      title: "Dashboard",
      translateKey: "nav.dashboard",
      icon: "home",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "patients",
      path: "/patients",
      title: "Patients",
      translateKey: "nav.patients",
      icon: "users",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "visits",
      path: "/visits",
      title: "Visits",
      translateKey: "nav.visits",
      icon: "activity",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "appointments",
      path: "/appointments",
      title: "Appointments",
      translateKey: "nav.appointments",
      icon: "calendar",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "lab.orders",
      path: "/lab-orders",
      title: "Lab Orders",
      translateKey: "nav.lab.orders",
      icon: "flask",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
    {
      key: "vaccinations",
      path: "/vaccinations",
      title: "Vaccinations",
      translateKey: "nav.vaccinations",
      icon: "shield",
      type: NAV_ITEM_TYPE_ITEM,
      authority: ["readOnly"],
      subMenu: [],
    },
  ],
};
